import { metadata as Metadata } from 'next';

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function AboutLayout({ children }) {
  return (
    <>
      <nav>About NavBar</nav>
      {children}
    </>
  );
}
